Draft: Feature/source command
Xithrius/Xythrion pull request #69
Opened 2023-10-21 05:10 UTC by fisher60

Initial version of source command. Needs some additional testing to verify changes, but is otherwise ready to go.

2023-10-21 05:10 UTC, fisher60 commented
Addresses #7

2023-10-21 20:41 UTC, GDWR requested changes

2023-10-21 20:41 UTC, GDWR commented on xythrion/bot/utils/converters.py
> +            return cog
```suggestion
        if cog := ctx.bot.get_cog(argument):
            return cog
```

2023-10-21 20:41 UTC, GDWR commented on xythrion/bot/utils/converters.py
> +            return cmd
```suggestion
        if cmd := ctx.bot.get_command(argument):
            return cmd
```

2023-10-21 20:41 UTC, GDWR commented on xythrion/bot/extensions/info/source.py
> +    async def source_command(
maybe just name the function `source`, default behaviour is to use this as the command name

2023-10-21 20:41 UTC, GDWR commented on xythrion/bot/extensions/info/source.py
> +        source_item: SourceConverter = None,
Incorrect type? Should be `| None` or `Optional`

2023-10-21 21:07 UTC, ChrisLovering commented on xythrion/bot/extensions/info/source.py
> +        source_item: SourceConverter = None,
This is a limitation in Discord.py, if you typehint this to be `| None` then if the input fails the `SourceConverter` conversion, it will just be set to None, instead of erroring

2023-10-21 21:11 UTC, fisher60 commented on xythrion/bot/utils/converters.py
> +            return cog
Looks good, I will go with another suggestion of yours to make the return even more concise.

2023-10-21 21:32 UTC, fisher60 commented on xythrion/bot/extensions/info/source.py
> +        source_item: SourceConverter | None = None,
Someone else should test this change on their machine before merging/finalizing this PR. This typing allegedly should not work as stated in a previous comment, but the behavior with the `| None` typing is identical to the behavior without the `| None` typing. 

I saved my changes and rebuilt the container with `docker compose up bot --build` and still got the desired behavior where typing a command such as `^source asdfasdfasdf` links to the root of the repo, rather than a specific file in the codebase. I suspect this could be due to the way docker is caching the source code, but I am unable to produce the suspected issue with this code.

2023-10-23 10:20 UTC, ChrisLovering commented on xythrion/bot/extensions/info/source.py
> +        source_item: SourceConverter | None = None,
Ah, the reason for the difference in behaviour is because the source convertor you have defined as `-> SourceType | None`, where as in the bots we define it as `-> SourceType` and [raise a BadArgument](https://github.com/python-discord/bot/blob/main/bot/converters.py#L251-L253) if it could not be converted. This is why your implementation don't have the error path that the pydis bots do.

2023-11-13 19:57 UTC, Xithrius commented
@fisher60 fix

2023-12-28 22:46 UTC, GDWR commented
Would be good to add some more tests

2023-12-28 22:48 UTC, fisher60 commented
New extension brought down coverage a decent amount. In the future we should make a decision on how we would like to handle extension testing.

2023-12-28 22:57 UTC, merged